version: '3'
services:
  librarydb:
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    image: rogerbv9017/librarydb:latest
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - networkdev
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "librarydb", "-U", "admin"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  backend:
    image: rogerbv9017/librarybackend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      librarydb:
        condition: service_healthy
    command: bash -c "npx prisma migrate dev --name init && npm run start"
    volumes:
      - ./:/express_nodejs_prisma_postgresl
    networks:
      - networkdev
networks:
  networkdev: